import fs from 'node:fs/promises';
const schema = JSON.parse(await fs.readFile(new URL('../../config/quant-research.schema.json', import.meta.url), 'utf8'));

/** type → directory (without trailing slash). Includes the two non-schema types this wiki uses. */
export const TYPE_DIRS = Object.fromEntries(schema.page_types.map(t => [t.name, t.path_prefixes[0].replace(/\/$/, '')]));
TYPE_DIRS.concept = 'concepts';
TYPE_DIRS.note = 'notes';

export const DIR_TYPES = Object.fromEntries(Object.entries(TYPE_DIRS).map(([type, dir]) => [dir, type]));
export const PAGE_TYPES = Object.keys(TYPE_DIRS);
export const RELATION_FIELDS = schema.link_types.map(t => t.name);

export const TYPE_LABELS = {
  source: '文献', paper: '论文解读', report: '研报解读', claim: '观点', hypothesis: '假设',
  factor: '因子', strategy: '策略', experiment: '实验', dataset: '数据集', security: '证券',
  industry: '行业', theme: '主题', metric: '指标', institution: '机构', concept: '概念', note: '笔记',
};

const WORD = '\\p{Ll}\\p{Lm}\\p{Lo}\\p{M}\\p{N}';
const KEEP_RE = new RegExp(`[^${WORD}.\\s_\\-]`, 'gu');

/** Mirror of gbrain's slugifySegment (vendor/gbrain/src/core/sync.ts). */
export function normalizeSegment(segment) {
  return segment
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[֑-ׇ]/g, '')
    .normalize('NFC')
    .toLowerCase()
    .replace(KEEP_RE, '')
    .replace(/[\s]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

export function normalizeSlug(input) {
  return String(input ?? '')
    .replace(/\\/g, '/')
    .replace(/^\.?\//, '')
    .replace(/\.mdx?$/i, '')
    .split('/')
    .map(normalizeSegment)
    .filter(Boolean)
    .join('/');
}

const SLUG_RE = /^[\p{L}\p{N}_\-.]+(\/[\p{L}\p{N}_\-.]+)*$/u;

export function isValidSlug(slug) {
  return typeof slug === 'string'
    && slug.length > 0
    && slug.length <= 200
    && SLUG_RE.test(slug)
    && slug.split('/').every(segment => !/^\.+$/.test(segment));
}

/** Directory the slug lives in, or null for root-level pages. */
export function dirForSlug(slug) {
  return slug.includes('/') ? slug.split('/')[0] : null;
}

export function typeForSlug(slug) {
  const dir = dirForSlug(slug);
  return dir ? (DIR_TYPES[dir] ?? null) : 'note';
}

export function dirForType(type) {
  return TYPE_DIRS[type] ?? null;
}

/** Pages generated by the pipeline must not be edited by hand. */
export function editability(slug) {
  if (typeForSlug(slug) === 'source') return { editable: false, reason: '文献全文由导入生成，阅读笔记可在文献页单独添加' };
  if (slug === '文献目录') return { editable: false, reason: '文献目录在每次索引时自动重建' };
  return { editable: true, reason: null };
}

/** Parse a relation value: "slug" or "[[slug|label]]" → normalized slug. */
export function relationTarget(value) {
  return normalizeSlug(String(value).replace(/^\[\[|\]\]$/g, '').split('|')[0].trim());
}
